### ISSUE TITLE
About the test dataset

### ISSUE THREAD

**Issue by Albelt** [huangyjhust/3D-RU-Net#11]
Hi!
   Thanks for your great work, the model and weights you released seems to segment the Colorectal Tumor directly, right?
![image](https://user-images.githubusercontent.com/35684393/55299175-5ae60e80-5464-11e9-8eaf-d8761c517987.png)
However, I found that the label you provide contains colorectal tissue's region rather than tumor's region, is the label wrong or maybe I misunderstand the model?
![image](https://user-images.githubusercontent.com/35684393/55299637-5f132b80-5466-11e9-9a3d-26480acea9bd.png)

**Comment by huangyjhust** [comment]
According to the radiologists that annotated the dataset, the label is precisely the cancerous colorectal tissue's region, not colorectal tissue's region.

**Comment by Albelt** [comment]
Got it, thank you!
