### ISSUE TITLE
ValQuarter

### ISSUE THREAD

**Issue by JeyzerMC** [huangyjhust/3D-RU-Net#2]
In the file `Step4_3D_RU_Net_Predict.py`, at line 79, fifth at the start of the main, (commit 5897bb8e18c524f6d8f895a811d0633b58d511e6), you do the following:
```
ValPatient= PatientNames[ ValQuarter*NumVal : (ValQuarter+1)*NumVal : ]
```
However, `ValQuarter` is not defined anywhere on the file, causing the error:
`E0602:Undefined variable 'ValQuarter'`.

What is the intended value for ValQuarter?

**Comment by huangyjhust** [comment]
Thank you and this issue is fixed. 
Actually I transferred the code from our Linux workstation to my Windows PC for code uploading, therefore some parts of the code need to be rectified.
