### ISSUE TITLE
Import FindFiles error

### ISSUE THREAD

**Issue by JeyzerMC** [huangyjhust/3D-RU-Net#3]
File `Step1_PreProcessing.py`, you do: `from FindFiles import findfiles` in the import section.

FindFiles not being a pip module, I assume it's a custom python file you wrote that was not uploaded as part of this repository.

The method findfiles is however used throughout the file, what is the intended use and output of this file?

**Comment by huangyjhust** [comment]
Thank you and this issue is fixed.
However the preprocessing code is just for illustration, since that we just uploaded the data in .mhd format to erase patient information, and this code shows how we generate .mhd from .dcm.
